data_dir: 'data'
output_dir: 'output'

dataset_name: panda
slide_list: 'data/panda/slide_list.txt'

step_size: 256
patch_size: 256

flags:
  seg: True
  patch: True
  stitch: True
  no_auto_skip: False
  verbose: False

seg_params:
  seg_level: -1
  sthresh: 8
  mthresh: 7
  close: 4
  use_otsu: False
  save_mask: True

filter_params:
  a_t: 100
  a_h: 16
  max_n_holes: 8

vis_params:
  vis_level: -1
  line_thickness: 100

patch_params:
  patch_level: 0
  white_thresh: 5
  black_thresh: 40
  use_padding: True
  contour_fn: 'four_pt'
  save_patches_to_disk: True
  format: 'png'
  draw_grid: True
  bg_color:
    - 255
    - 255
    - 255