data_dir: 'data'
output_dir: 'output'

dataset_name: 'panda'
slide_list: 'data/panda/slide_list.txt'
resume: True

wandb:
  project: 'hs2p'
  exp_name: 'panda'
  username: 'clemsg'

flags:
  seg: True
  patch: True
  stitch: True
  auto_skip: False
  verbose: False

seg_params:
  seg_level: -1
  sthresh: 8
  mthresh: 7
  close: 4
  use_otsu: True
  save_mask: True

filter_params:
  a_t: 16
  a_h: 4
  max_n_holes: 8

vis_params:
  vis_level: -1
  line_thickness: 200

patch_params:
  patch_level: 0
  patch_size: 4096
  step_size: 4096
  white_thresh: 5
  black_thresh: 50
  use_padding: True
  contour_fn: 'pct'
  drop_holes: False
  tissue_thresh: 0.1
  save_patches_to_disk: True
  format: 'jpg'
  draw_grid: True
  bg_color:
    - 214
    - 233
    - 238