data_dir: 'data'
output_dir: 'output'

dataset_name: tcga_brca
slide_list: 'data/tcga_brca/toy_list.txt'

step_size: 4096
patch_size: 4096
patch_level: 0
process_list:

flags:
  seg: True
  patch: False
  stitch: False
  no_auto_skip: False
  verbose: False

seg_params:
  seg_level: -1
  sthresh: 32
  mthresh: 7
  close: 4
  use_otsu: False
  keep_ids:
  exclude_ids:
  save_mask: True

filter_params:
  a_t: 10
  a_h: 4
  max_n_holes: 8

vis_params:
  vis_level: -1
  line_thickness: 200

patch_params:
  white_thresh: 5
  black_thresh: 40
  use_padding: True
  contour_fn: 'pct'
  drop_holes: False
  tissue_thresh: 0.1
  save_patches_to_disk: False
  format: 'png'
  draw_grid: True
  bg_color:
    - 214
    - 233
    - 238