defaults:
  - default
  - _self_

dataset_name: 'tcga_brca'
slide_list: 'data/tcga_brca/slide_list.txt'
resume: False
experiment_name: 'otsu'

wandb:
  exp_name: 'tcga_brca'

patch_params:
  save_patches_to_disk: True