defaults:
  - default
  - _self_

dataset_name: tcga_brca
slide_list: 'data/tcga_brca/slide_list.txt'
resume: False
experiment_name: 'clam'

wandb:
  exp_name: 'tcga_brca_clam'

seg_params:
  use_otsu: False

patch_params:
  contour_fn: 'four_pt'
  drop_holes: True
  save_patches_to_disk: True